language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
install:
  - travis_retry npm install -g esy@0.1.9
  - travis_retry npm install -g yarn
  - travis_retry make bootstrap
script:
  - travis_wait make ci
cache:
  # default timeout is 180 but it takes longer sometimes
  timeout: 360
  # this caches esy build store and esy install cache too
  directories:
  - $HOME/.esy/
