// flow-typed signature: 141a1e3bb5b83a36ef6cd35b7c44ff22
// flow-typed version: <<STUB>>/loud-rejection_v1.6.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loud-rejection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loud-rejection' {
  declare module.exports: () => void;
}
