// flow-typed signature: dc2cc110b8fe556669c2f9c9e93a5121
// flow-typed version: <<STUB>>/outdent_v0.4.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'outdent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'outdent' {
  declare module.exports: (Array<string>) => string;
}
