// flow-typed signature: a9349f282fea20a695b8ab8e846ab55d
// flow-typed version: <<STUB>>/yaml-js_v0.2.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yaml-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yaml-js' {
  import type {Node} from 'yaml-js/lib/nodes';
  declare export function compose(string): Node;
  declare export function load(string): Node;
}

declare module 'yaml-js/lib/nodes' {
  declare export type Mark = {
    line: number,
    column: number,
  };

  declare export class Node {
    start_mark: Mark;
    end_mark: Mark;
  }

  declare export class MappingNode extends Node {
    tag: 'tag:yaml.org,2002:map';
    value: Array<[Node, Node]>;
    start_mark: Mark;
    end_mark: Mark;
  }

  declare export class SequenceNode extends Node {
    tag: 'tag:yaml.org,2002:seq';
    value: Array<Node>;
    start_mark: Mark;
    end_mark: Mark;
  }

  declare export class ScalarNode extends Node {
    tag: string;
    value: string;
    start_mark: Mark;
    end_mark: Mark;
  }
}
