// flow-typed signature: 34a236cac2602bafa24427e21060af46
// flow-typed version: <<STUB>>/@vx/text_v0.0.159/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/text/build/fragments/textOutlineProps' {
  declare module.exports: any;
}

declare module '@vx/text/build/fragments/textProps' {
  declare module.exports: any;
}

declare module '@vx/text/build/index' {
  declare module.exports: any;
}

declare module '@vx/text/build/Text' {
  declare module.exports: any;
}

declare module '@vx/text/build/text/TextBackground' {
  declare module.exports: any;
}

declare module '@vx/text/build/text/TextOutline' {
  declare module.exports: any;
}

declare module '@vx/text/build/text/TextWrap' {
  declare module.exports: any;
}

declare module '@vx/text/build/util/getStringWidth' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/text/build/fragments/textOutlineProps.js' {
  declare module.exports: $Exports<'@vx/text/build/fragments/textOutlineProps'>;
}
declare module '@vx/text/build/fragments/textProps.js' {
  declare module.exports: $Exports<'@vx/text/build/fragments/textProps'>;
}
declare module '@vx/text/build/index.js' {
  declare module.exports: $Exports<'@vx/text/build/index'>;
}
declare module '@vx/text/build/Text.js' {
  declare module.exports: $Exports<'@vx/text/build/Text'>;
}
declare module '@vx/text/build/text/TextBackground.js' {
  declare module.exports: $Exports<'@vx/text/build/text/TextBackground'>;
}
declare module '@vx/text/build/text/TextOutline.js' {
  declare module.exports: $Exports<'@vx/text/build/text/TextOutline'>;
}
declare module '@vx/text/build/text/TextWrap.js' {
  declare module.exports: $Exports<'@vx/text/build/text/TextWrap'>;
}
declare module '@vx/text/build/util/getStringWidth.js' {
  declare module.exports: $Exports<'@vx/text/build/util/getStringWidth'>;
}
