// flow-typed signature: b23bd52185d63205f8b211af8fe857fc
// flow-typed version: <<STUB>>/react-icons_v2.2.7/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-icons/lib/md' {
  declare module.exports: any;
}
